### ISSUE TITLE
cannot connect to ENDPOINT AUTOMATICALLY on APP START

### ISSUE THREAD

**Issue by ashleshp** [lxcao/flutter_mqtt_aws_iot#1]
Is there a way where we can connect our client to endpoint automatically on app start????

**Comment by lxcao** [comment]
Put the following configure and connect in the initState():     

awsIOTmanager = MQTTServerClientManager {
        host: demoAWSIOTEndpoint,
        topic: demoAWSIOTTopic,
        identifier: demoVIN,
        state: currentAWSIOTState);
    awsIOTmanager.initializeMQTTClient();
    awsIOTmanager.connect();

Detail check: https://github.com/lxcao/flutter_driving_cycle.git
